import { describe, expect, it } from "vitest";
import { initialWorkQueueState, workQueueReducer, type WorkQueueState } from "./work-queue-scenario";
function run(state: WorkQueueState, limit = 100) { let current = workQueueReducer(state, { type: "start" }); for (let i = 0; i < limit && current.playback !== "completed"; i += 1) current = workQueueReducer(current, { type: "tick" }); return current; }
describe("workQueueReducer", () => {
  it("発行したMessageを競合Consumerが分担して処理する", () => { const result = run({ ...initialWorkQueueState, publicationVolume: 16 }); expect(result).toMatchObject({ playback: "completed", published: 16, queued: 0 }); expect(result.processed.a + result.processed.b).toBe(16); expect(Math.abs(result.processed.a - result.processed.b)).toBeLessThanOrEqual(1); });
  it("Consumer Aを停止するとConsumer Bだけが処理する", () => { const stopped = workQueueReducer(initialWorkQueueState, { type: "toggle-consumer", consumer: "a" }); const result = workQueueReducer(workQueueReducer(stopped, { type: "start" }), { type: "tick" }); expect(result.processed).toEqual({ a: 0, b: 2 }); expect(result.queued).toBe(2); });
  it("両Consumerの停止中はbacklogが蓄積し、復旧後に完了する", () => { let state = { ...initialWorkQueueState, publicationVolume: 8 }; state = workQueueReducer(state, { type: "toggle-consumer", consumer: "a" }); state = workQueueReducer(state, { type: "toggle-consumer", consumer: "b" }); state = workQueueReducer(state, { type: "start" }); state = workQueueReducer(state, { type: "tick" }); state = workQueueReducer(state, { type: "tick" }); expect(state).toMatchObject({ playback: "running", published: 8, queued: 8, processed: { a: 0, b: 0 } }); state = workQueueReducer(state, { type: "toggle-consumer", consumer: "b" }); expect(run(state)).toMatchObject({ playback: "completed", queued: 0, processed: { a: 0, b: 8 } }); });
  it("Pause中のtickでは状態を変更しない", () => { const paused = workQueueReducer(workQueueReducer(initialWorkQueueState, { type: "start" }), { type: "pause" }); expect(workQueueReducer(paused, { type: "tick" })).toBe(paused); });
  it("実行中は発行量を変更せず処理量は変更できる", () => { const running = workQueueReducer(initialWorkQueueState, { type: "start" }); expect(workQueueReducer(running, { type: "set-publication-volume", value: 40 })).toBe(running); expect(workQueueReducer(running, { type: "set-processing-amount", value: 4 }).processingAmount).toBe(4); });
  it("Resetで合成した初期状態へ戻る", () => { expect(workQueueReducer(run({ ...initialWorkQueueState, publicationVolume: 8 }), { type: "reset" })).toEqual(initialWorkQueueState); });
});
